{
 "title": "Worker",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"worker-server\"}"
    }
   ]
  },
  {
   "title": "Worker Start Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds{}" }
   ]
  },
  {
   "title": "Worker Submit Queue Full/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(dolphinscheduler_worker_submit_queue_is_full_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Overload Increase/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "increase(dolphinscheduler_worker_overload_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Running Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "dolphinscheduler_worker_running_task_gauge{}"
    }
   ]
  },
  {
   "title": "Task Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dolphinscheduler_task_execution_count_total)"
    }
   ]
  },
  {
   "title": "Task Successful Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dolphinscheduler_task_execution_count_total{result=\"success\"}) / sum(dolphinscheduler_task_execution_count_total) * 100"
    }
   ]
  },
  {
   "title": "Task Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "millse" } },
   "yaxes": [
    { "format": "millse" }
   ],
   "targets": [
    {
     "expr": "rate(dolphinscheduler_task_execution_timer_seconds_sum[1m])/rate(dolphinscheduler_task_execution_timer_seconds_count[1m])",
     "legendFormat": "avg ({{exception}})"
    },
    {
     "expr": "dolphinscheduler_task_execution_timer_seconds_max",
     "legendFormat": "max ({{exception}})"
    }
   ]
  },
  {
   "title": "Task Execution Total/Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execution_count_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(dolphinscheduler_task_execution_count_total{result=\"success\"}[1m])",
     "legendFormat": "Successful"
    }
   ]
  },
  { "title": "Task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Shell Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"SHELL\"}[1d]))",
     "legendFormat": "SHELL"
    }
   ]
  },
  {
   "title": "Unkown Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"unknown\"}[1d]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Condition Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"CONDITIONS\"}[1d]))",
     "legendFormat": "CONDITIONS"
    }
   ]
  },
  {
   "title": "Blocking Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"BLOCKING\"}[1d]))",
     "legendFormat": "BLOCKING"
    }
   ]
  },
  {
   "title": "DATAX Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"DATAX\"}[1d]))",
     "legendFormat": "DATAX"
    }
   ]
  },
  {
   "title": "DATA_QUALITY Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"DATA_QUALITY\"}[1d]))",
     "legendFormat": "DATA_QUALITY"
    }
   ]
  },
  {
   "title": "DATA_QUALITY Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"DATA_QUALITY\"}[1d]))",
     "legendFormat": "DATA_QUALITY"
    }
   ]
  },
  {
   "title": "DEPENDENT Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"DEPENDENT\"}[1d]))",
     "legendFormat": "DEPENDENT"
    }
   ]
  },
  {
   "title": "EMR Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"EMR\"}[1d]))",
     "legendFormat": "EMR"
    }
   ]
  }
 ]
}